# Generated by Django 3.2.5 on 2021-09-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210622_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='code',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
